### ISSUE TITLE
Agregar Agenda Legislativa LXIII

### ISSUE THREAD

**Issue by ppaez** [siguealcongreso/sitioweb#2]
#### Descripción:
Escribir un artículo titulado _Agenda Legislativa_ en la sección monitoreo, que permita a los usuarios comparar los temas prioritados acordados al inicio de la legislatura contra los temas abordados en las iniciativas que se presentan y/o aprueban a lo largo de los tres años.

#### Resultado esperado:
- Que aparezca listado en la sección monitoreo un texto corto que dé idea de qué hay adentro.
- Que su contenido sirva de referencia (Informar cuáles son los temas principales y transversales de esta legislatura) y como explicación (Aprender cómo se crea, quiénes participan en su creación, cuándo se crea, qué ley   regula).
-  Incluir enlace al documento PDF del acuerdo legislativo.

#### Por definir:
- El texto corto que aparece en la lista de la sección monitoreo junto a Resumen, Por áreas, Iniciativas sin tema, Por comisiones, etc.
- Si es relevante el orden en que aparezca esta página en el listado ¿Que sea el primer elemento? ¿Que vaya después de cuál?.
- Si se prefiere que referencia y explicación vayan en páginas separadas.  La referencia va a ser específica a cada legislatura, la explicación que sea general para cualquier legislatura.

#### Solución sugerida:
- Incluir un renglón con el texto `<!--more-->` que sirve para delimitar el texto corto del resto del contenido.

**Comment by ppaez** [comment]
El texto está muy bien, nada más un par de cosas:

1. Agrega un bloque de metainformación al inicio del archivo .md. Sin la metainformación, se usa el título del sitio web para esta página:

![titulo-del-sitio](https://github.com/siguealcongreso/sitioweb/assets/692448/902cfce0-0cfe-47da-ba49-ca96284c3844)

   Y en el  listado aparece sin título:

![sin-titulo-resumen-largo](https://github.com/siguealcongreso/sitioweb/assets/692448/f480508d-b5d9-45d9-a18e-93e91814c738)

   Podrías usar el comando `hugo new content content/monitoreo/agenda-legislativa-lxiii.md` para crear el bloque de metainformación al inicio y el archivo vacío.  Este nombre del archivo sigue el patrón de los demás archivos que ya están y da la ruta del enlace a esta página (/monitoreo/agenda-legislativa-lxiii/).

2.  Agrega un texto corto y el bloque `<!--more-->`. Sin el bloque hugo usa mucho texto del artículo en el listado como se ve arriba.  Mi sugerencia para el texto es ``Temas principales y transversales de esta legislatura.``

**Comment by Armandotrsg** [comment]
> El texto está muy bien, nada más un par de cosas:
> 
> 1. Agrega un bloque de metainformación al inicio del archivo .md. Sin la metainformación, se usa el título del sitio web para esta página:
> 
> ![titulo-del-sitio](https://user-images.githubusercontent.com/692448/264813228-902cfce0-0cfe-47da-ba49-ca96284c3844.png)
> 
> Y en el listado aparece sin título:
> 
> ![sin-titulo-resumen-largo](https://user-images.githubusercontent.com/692448/264813283-f480508d-b5d9-45d9-a18e-93e91814c738.png)
> 
> Podrías usar el comando `hugo new content content/monitoreo/agenda-legislativa-lxiii.md` para crear el bloque de metainformación al inicio y el archivo vacío. Este nombre del archivo sigue el patrón de los demás archivos que ya están y da la ruta del enlace a esta página (/monitoreo/agenda-legislativa-lxiii/).
> 
> 2. Agrega un texto corto y el bloque `<!--more-->`. Sin el bloque hugo usa mucho texto del artículo en el listado como se ve arriba.  Mi sugerencia para el texto es `Temas principales y transversales de esta legislatura.`

Ok, ahorita lo hago, es que no me habías comentado aún si el texto estaba bien, por eso solo lo diseñé en Markdown normal
