### ISSUE TITLE
Agregar Facultades del Congreso

### ISSUE THREAD

**Issue by ppaez** [siguealcongreso/sitioweb#3]
#### Descripción:
Escribir un artículo titulado *Facultades del Congreso* en la sección Organización del Congreso.

#### Resultado esperado:
- Que sea explicación para aprender las demás funciones que realiza el Congreso y que son poco conocidas, además de crear iniciativas de ley.
- Incluir enlace al artículo o artículos relevantes de la Ley Orgánica del Poder Legislativo del Estado de Jalisco.

#### Por definir:
- Enlaces a artículos relacionados ya existentes o que sería bueno crear.

#### Solución sugerida:
- Considerar el uso de `toc: true` en la metainformación para que aparezca un índice de contenido.

**Comment by Armandotrsg** [comment]
# Respuesta a las preguntas

## Facultades del congreso

1. **¿Hay algunos temas en los cuales no puede legislar el Congreso?**
   - Sí, el Congreso no puede legislar en materias que son concedidas al Congreso de la Unión conforme al Pacto Federal en la Constitución Política de los Estados Unidos Mexicanos. (Fracción I)

2. **¿Con cuáles facultades el Congreso puede regular al Poder Ejecutivo?**
   - Facultar al Ejecutivo para representar la Entidad en ciertos casos y autorizar los convenios que celebre el Ejecutivo. (Fracción II)
   - Autorizar al titular del Poder Ejecutivo y a sus entes públicos para celebrar ciertos actos jurídicos. (Fracción XI)
   - Pedir informes al Gobernador sobre cualquier ramo de la administración. (Fracción XXIX)
   - Citar a los titulares de dependencias del Poder Ejecutivo para que informen sobre diversos asuntos. (Fracción XXX)

3. **¿En qué puede regular el Congreso al Poder Judicial?**
   - Elegir en libertad soberana a los Magistrados del Supremo Tribunal de Justicia, a los titulares del Consejo de la Judicatura, y a los Magistrados del Tribunal de Justicia Administrativa. (Fracción IX)
   - Resolver sobre las renuncias de los magistrados del Poder Judicial y de los consejeros integrantes del Consejo de la Judicatura. (Fracción XV)
   - Conceder o negar licencias a los magistrados del Poder Judicial. (Fracción XVII)

4. **¿En qué regula el Congreso a los municipios?**
   - Fijar la división territorial, política y administrativa del Estado, incluyendo la denominación de los municipios. (Fracción III)
   - Autorizar a los Ayuntamientos y a sus entes públicos para celebrar ciertos actos jurídicos. (Fracción XI)

5. **¿Cuáles facultades del Congreso son para regularse a sí mismo?**
   - Expedir su Ley Orgánica, formar sus reglamentos, y dictar disposiciones para el buen funcionamiento de sus oficinas. (Fracción XXXI)
   - Presidir la junta preparatoria para instalar la nueva legislatura. (Fracción XXXIV)
   - Elaborar el proyecto de presupuesto del Poder Legislativo y ejercerlo con autonomía. (Fracción XXIV)

6. **¿Cuáles cargos le toca elegir al Congreso? Haz una lista con el nombre del cargo, el organismo al que pertenece y si se requiere una cantidad específica de votos.**
   - Magistrados del Supremo Tribunal de Justicia, Tribunal de Justicia Administrativa, y titulares del Consejo de la Judicatura - Poder Judicial. (Fracción IX)
   - Titulares de los órganos internos de control de organismos autónomos - Organismos Autónomos. Se requiere el voto de las dos terceras partes de los diputados presentes. (Fracción X)
   - Presidente y consejeros ciudadanos de la Comisión Estatal de Derechos Humanos - Comisión Estatal de Derechos Humanos. Se requiere la aprobación de las dos terceras partes de los diputados presentes. (Fracción XII)
   - Fiscal General - Poder Ejecutivo. (Fracción XVIII)
   - Auditor Superior y auditores especiales - Auditoría Superior del Estado. Se requiere el voto de las dos terceras partes de los diputados integrantes. (Fracción XXV)
   - Presidente y comisionados del Instituto de Transparencia, Información Pública y Protección de Datos Personales - Instituto de Transparencia. Se requiere la aprobación de las dos terceras partes de los diputados integrantes. (Fracción XXXIII)
   - Fiscal Especializado en materia de Delitos Electorales y Fiscal Especializado en Combate a la Corrupción - Poder Ejecutivo. Se requiere el voto de las dos terceras partes de los diputados integrantes. (Fracción XXXVI)
   - Procurador de Desarrollo Urbano - Estado. Se requiere el voto de las dos terceras partes de los diputados integrantes. (Fracción XXXVII)
