### ISSUE TITLE
Agregar el listado de temas a la sección monitoreo

### ISSUE THREAD

**Issue by ppaez** [siguealcongreso/sitioweb#39]
## Descripción:
Se desea mejorar la página `/temas` para el proyecto Entérate,   para que ayude a estandarizar los temas y a encontrar los que necesiten corrección.

Se quiere hacer más útil la información que se muestra y agregar esta página junto a los demás listados en la sección monitoreo.  Esta página es generada por la  taxonomía temas.

## Resultado esperado:
1. Aparece como una tarjeta más en la sección monitoreo
2. No muestra las iniciativas a las que les falta tema y resumen
3. No muestra iniciativas que van en la sección municipios
4. Los encabezados son el valor de un tema seguido de la cantidad de iniciativas que tienen ese mismo tema.
5. Los encabezados van ordenados alfabéticamente.
6. Después de cada encabezado de un tema, se ve una lista de renglones a dos columnas. Cada renglón es una iniciativa. Las columnas son Resumen (al final el número de iniciativa entre paréntesis) y Área.
7. Cada renglón tiene borde visible y una mínima separación vertical.
8. El cuadro donde va el resumen y donde va el área tienen fondo gris claro, similar a la ficha de iniciativa.
9. El cuadro del resumen va coloreado en verde para las iniciativas aprobadas.
10. La lista de iniciativas en cada tema va ordenada por el número de iniciativa.
11. Cuando Área tiene dos o más valores, se muestran separados por una coma.
12. En pantallas pequeñas, la lista cambia a una sola columna: Resumen va seguido del área.

## Solución sugerida:
- Modificar la plantilla `layouts/temas/terms.html` existente.
- Implementar la lista de iniciativas de un tema con la clases `container`, `row` y `col` de Bootstrap, formando renglones con dos columnas.
- La columna de Área usa el 25% del ancho en el punto de quiebre 'md' y mayores, la otra columna usa el resto del ancho disponible. La columna de Area usa todo el ancho en resoluciones debajo del  punto de quiebre `md`.
- Filtro para el tema "Pendiente": `{{ if ne .Page.Title "Pendiente" }}`
- Filtro para iniciativas de los municipios `{{ if eq (index .Page.Params.municipios 0) "" }}`
- Para ordenar por número de proceso: `.Pages.ByParam "numero"`
- Algunos resúmenes incluyen Markdown, usar la función `markdownify` para interpretarlo
- Para juntar los valores de Área: `delimit . ", "`
- Para colorear el cuadro de resumen de las iniciativas aprobadas en verde, y en caso contrario en gris: `class="col {{ if eq .Params.estado "Aprobado" }}bg-success-subtle"{{ else }}bg-light{{ end }}"`

Para listar esta página en la sección monitoreo:
- Crear `content/monitoreo/temas.md` con un enlace "Lista de todas las iniciativas agrupadas por tema" que lleva a la ruta `/temas` en forma similar a `content/monitoreo/mensual.md`.

**Comment by Armandotrsg** [comment]
@ppaez Quería empezar a trabajar en ello, pero la sección de temas en mi local está vacía, creo que es parte del contenido generado dinámicamente.
