### ISSUE TITLE
Convertir "Acerca de" a sección

### ISSUE THREAD

**Issue by ppaez** [siguealcongreso/sitioweb#9]
## Descripción:
La página inicial tiene un enlace *Acerca de* a la ruta `/acerca`, la cual es una página que tiene los siguientes encabezados:
- Introducción
- ¿Por qué es importante seguir/observar al Congreso de Jalisco?
- ¿Cómo surgió Sigue al Congreso?
- ¿Qué impulsamos?
- ¿En qué creemos en Sigue al Congreso?
- Ver también

Esta página se implementó muy al principio mediante los archivos  `content/acerca/index.html` y `content/acerca/base.css`.  Utiliza una paleta de colores que se usó anteriormente en los mensajes de redes  y no usa el estilo del resto del sitio.

Se quiere transformar esta página a archivos .md, donde cada archivo contenga un encabezado y su texto correspondiente de la página actual.

El encabezado *Ver también* se elimina, el acceso al único enlace *Trabajo realizado* se va a integrar en otra sección mediante otro Issue.

## Resultado esperado:
1. Una sección en la ruta `/acerca` en la cual se listan los encabezados a manera de tarjetas, similar a como se listan en las secciones `/monitoreo`, `/mensual/lxiii/`, `/docs` del sitio.
2.  Que los encabezados sigan el mismo orden actual.
3.  Que las páginas en esta sección utilicen una de las plantillas del tema del siito y se vean integradas al resto del sitio, ahora y cuando se actualice el tema más adelante.
4.  Que más adelante se puedan agregar otros encabezados, como Misión, Visión, etc., agregando un nuevo archivo .md y que estas nuevas páginas aparezcan listadas automáticamente e intercaladas donde se desee.

## Por definir:
Las plantillas actuales para el listado de páginas de una sección, muestran un fragmento del texto inicial de cada página. Este fragmento a veces puede ser muy extenso. Hay que observar el listado en esta nueva sección, y si hace falta usar un bloque `<~--more-->` en una o más páginas para delimitar el fragmento adecuado a mostrar.

## Solución sugerida:
1. Crear `content/acerca/_index.md` para declarar la nueva sección. El título puede ser *Acerca de* y el contenido algo como "Conoce sobre Sigue al Congreso".
2. Crear los archivos:
    - `content/acerca/introduccion.md`
    - `content/acerca/por-que-seguir-al-congreso.md`
    - `content/acerca/como-surgio-sigue-al-congreso.md`
    - `content/acerca/que-impulsamos.md`
    - `content/acerca/en-que-creemos.md`
3. En estos archivos `title` va a ser el encabezado completo actual, y van a contener el texto que corresponde a ese encabezado, con negritas o izquierdilla si tienen en el texto actual.
5. Usar `weight` en la metainformación de estos archivos con valores 10, 20, 30. etc. según el orden actual.  Hugo ordena las páginas de una sección por esta variable si existe, en orden ascendente.  Cuando más adelante se agregue otra página a esta sección, se podrá listar entre las existentes usando valores como 15, 25, etc.
6. Remover los archivos `content/acerca/index.html` y `content/acerca/base.css`.

**Comment by Armandotrsg** [comment]
¿Dónde coloco el hipervínculo para el archivo de `content/trabajo.html` o ese también se borra junto con las imágenes?

**Comment by Armandotrsg** [comment]
Por el momento no le puse descripción a las tarjetas que se muestran en `content/acerca/_index.md`:

<img width="982" alt="Captura de pantalla 2023-09-14 a la(s) 18 04 14" src="https://github.com/siguealcongreso/sitioweb/assets/105229933/adec38e4-c7d9-45b1-b92c-50066bd79359">

**Comment by ppaez** [comment]
Vamos a dejar los archivos `content/acerca/trabajo.html`, `content/acerca/*.png` y `content/acerca/trabajo.html` sin tocar por ahora. En otro Issue vamos a modificarlos.

Está muy bien que no haya texto antes del bloque `<!--more-->` en cada archivo .md creado, puede quedarse así. De esta manera cada tarjeta muestra nada más el enlace *Leer más...*, no hace falta más texto además de los encabezados.  Los encabezados `¿Qué impulsamos?` y `¿En qué creemos?` están más cortos que el original, pero ya vistos en el conjunto de las tarjetas me parecen bien, déjalos así.

Les estás poniendo un texto en `description` a cada tarjeta, ese texto es muy útil cuando se comparte el enlace, excelente.  Crea el PR.
